### ISSUE TITLE
Example app using ng2-redux and Apollo

### ISSUE THREAD

**Issue by alexthewilde** [angular-redux/example-app#1]
Hey @SethDavenport! I've used your example app to work on an integration of ng2-redux with the Apollo client ([repo](https://github.com/alexthewilde/angular-redux-apollo-example)).

The major goal was to get the Apollo client to use an existing Redux store in an angular app. This is currently not possible with ngrx/store which I've used before ([see issue](https://github.com/apollostack/apollo-client/issues/593)). Since ng2-redux is wrapping itself around Redux rather than re-implementing it, the integration just works out of the box, which is kind of awesome!

One small issue though: I couldn't get the example app to run with the current HEAD, which could be related to the  `angular-redux` renaming. So I based my example app off of a previous version that still uses `ng2-redux`.

In any case, big thanks to you for all your work on angular-redux!

**Comment by SethDavenport** [comment]
Hey - yeah the @angular-redux renaming is still in progress - sorry for the disruption.

Thanks for the kind words, I'm glad this example was useful.  Ngrx is a great solution, but they're more of a 'curated reimplementation' of redux + select middlewares.  Our goal is to try and stay compatible with the broader ecosystem.

**Comment by SethDavenport** [comment]
The package rename is complete, this app should now work properly from HEAD.  Let me know if the new package names are still giving you problems.

**Comment by alexthewilde** [comment]
@SethDavenport I managed to migrate to `@angular-redux/store` without a glitch!
