### ISSUE TITLE
[Error] Supplied parameters do not match any signature of call target.

### ISSUE THREAD

**Issue by chunghha** [angular-redux/example-app#27]
Getting this error from fresh git clone'd local after yarn and npm start.

ERROR in example-app/src/app/store/store.module.ts (37,9): Supplied parameters do not match any signature of call target.

I am going to open a PR later.

**Comment by SethDavenport** [comment]
Yeah thanks - I believe this was due to a package/typings version mismatch for redux logger. I've merged your PR.

**Comment by chunghha** [comment]
@SethDavenport thanks for you quick response. And, I really appreciate your efforts on providing this nice example app which helps me a lot understand redux in angular.
