### ISSUE TITLE
Can't run master

### ISSUE THREAD

**Issue by nasreddineskandrani** [angular-redux/example-app#32]
Hi, 
The example is not working for me. I tried
1. clone the project
2. `yarn install`
3. `ng serve` (as doc mention) <- here problem with ng
had to `npm install ng`
then i retried `ng serve` <- still not working
error => `You have to be inside an angular-cli project in order to use the serve command.`
4. i checked the package.json script section
`yarn start` (it start but with error)
`ERROR in AppModule is not an NgModule` ....
env: windows 10 / node v6.9.5

**Comment by SethDavenport** [comment]
HI @nasreddineskandrani 

A fresh clone works fine for me on Mac OS X.  T

Some notes on the messages you reported:

*ng serve*

 Yes,  you need to have the `ng` command in your path.  However it's provided by the `@angular/cli` package, not the `ng` package. So try `npm i -g @angular/cli` instead.

Alternately you can run `yarn start` which uses the local version of `@angular/cli` from the project's `node_modules` folder.

*yarn start*

`ERROR in AppModule is not an NgModule` is a known incompatibility with older versions of Yarn and `@angular/cli` generated projects.  Please try updating to the latest version of yarn.

**Comment by nasreddineskandrani** [comment]
thank you
